Login functional
DradeFire/Cringe_ToDo__Android pull request #1
Opened 2023-03-22 18:44 UTC by FyrL29074

Реализация логина (Functional)

2023-03-23 07:54 UTC, DradeFire requested changes
Надо бы исправить

2023-03-23 07:54 UTC, DradeFire commented on app/src/main/java/com/cringeteam/todoproject/data/dto/loginRequest/LoginRequestMapper.kt
> +    fun format(request: LoginRequest): LoginRequestDto {
Это маппер, используй "map"

2023-03-23 07:54 UTC, DradeFire commented on app/src/main/java/com/cringeteam/todoproject/data/dto/loginRequest/LoginRequestMapper.kt
> +package com.cringeteam.todoproject.data.dto.loginRequest
Давай разделять модели сети и бд
Перенеси маппе и дто в /data/rest папку

2023-03-23 07:54 UTC, DradeFire commented on app/src/main/java/com/cringeteam/todoproject/data/dto/loginResponse/LoginResponseMapper.kt
> +class LoginResponseMapper {
Это маппер, используй "map"

2023-03-23 07:54 UTC, DradeFire commented on app/src/main/java/com/cringeteam/todoproject/domain/usecases/SendLoginRequestUseCase.kt
> +    // Зависимость от data слоя? лул? Или просто нет Dagger и вот так вот?
Именно
```suggestion
    // Зависимость от data слоя? лул? Или просто нет Dagger и вот так вот?
```

2023-03-23 07:54 UTC, DradeFire commented on app/src/main/java/com/cringeteam/todoproject/data/rest/api/Api.kt
> +    ): Single<LoginResponseDto>
Хммм
А ты точно тут не поймаешь еррор?)

(нету адаптера на rx штучки)

2023-03-29 08:21 UTC, DradeFire requested changes
+ у тебя lint не прошёл, почитай описание к нему

2023-03-29 08:21 UTC, DradeFire commented on app/build.gradle
> +    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
Такс, зачем эта библиотека?

2023-03-29 08:21 UTC, DradeFire commented on app/src/main/java/com/cringeteam/todoproject/presentation/features/loginScreen/LoginFragment.kt
> +            viewModel.screenState
Хмм, а зачем ComposideDisposable нужен?

2023-03-29 08:21 UTC, DradeFire commented on app/src/main/java/com/cringeteam/todoproject/presentation/features/loginScreen/LoginScreenState.kt
> +enum class LoginScreenState {
Думаю, можно вынести в отдельный слой, например, common

2023-03-29 13:03 UTC, FyrL29074 commented on app/src/main/java/com/cringeteam/todoproject/presentation/features/loginScreen/LoginFragment.kt
> +            viewModel.screenState
Факт. Исправил. + Добавил в BaseFragment его объявление

2023-03-29 13:03 UTC, FyrL29074 commented on app/build.gradle
> +    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
Моя ошибка, исправил

2023-03-29 14:12 UTC, DradeFire approved these changes

2023-03-29 14:13 UTC, merged